# Generated by Django 4.2.2 on 2023-08-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=20)),
                ('fabric', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=40)),
                ('fitting_type', models.CharField(max_length=20)),
                ('imported', models.BooleanField()),
                ('category_id', models.CharField(max_length=10)),
            ],
        ),
    ]
