# Generated by Django 4.2.2 on 2023-10-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoice/'),
        ),
    ]
