<<<<<<< Updated upstream
<<<<<<< Updated upstream
# Generated by Django 4.2.1 on 2023-10-04 09:21
=======
# Generated by Django 4.2.2 on 2023-10-08 10:37
>>>>>>> Stashed changes
=======
# Generated by Django 4.2.2 on 2023-10-08 10:37
>>>>>>> Stashed changes

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< Updated upstream
<<<<<<< Updated upstream
        ("api", "0005_generatedpdf"),
=======
        ('api', '0005_generatedpdf'),
>>>>>>> Stashed changes
=======
        ('api', '0005_generatedpdf'),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< Updated upstream
<<<<<<< Updated upstream
            name="Singer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="generatedpdf",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="invoice"),
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("duration", models.IntegerField()),
                (
                    "singer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sungby",
                        to="api.singer",
                    ),
                ),
=======
=======
>>>>>>> Stashed changes
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='generatedpdf',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoice'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sungby', to='api.singer')),
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
            ],
        ),
    ]
