# Generated by Django 4.2.2 on 2023-10-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_singer_alter_generatedpdf_pdf_file_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
