# Generated by Django 4.2.2 on 2023-10-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_song_title'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
