# Generated by Django 4.2.2 on 2023-10-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_movie_alter_song_singer_song_movie'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
    ]
