# Generated by Django 4.2.1 on 2024-01-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_student_country_student_zipcode_alter_student_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
    ]
