# Generated by Django 4.2.1 on 2024-01-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_carmodel_fueltype_alter_carmodel_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=100)),
            ],
            options={"ordering": ["headline"],},
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
            ],
            options={"ordering": ["title"],},
        ),
        migrations.DeleteModel(name="CarModel",),
        migrations.DeleteModel(name="FuelType",),
        migrations.AddField(
            model_name="article",
            name="publications",
            field=models.ManyToManyField(to="api.publication"),
        ),
    ]
