# Generated by Django 4.2.1 on 2024-01-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_article_publication_delete_carmodel_delete_fueltype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingalTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
