# Generated by Django 4.2.1 on 2024-01-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_singaltable_user"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
